"""
AI Responder — placeholder that does keyword search over KnowledgeChunks.

This is the ONE file that a teammate swaps out to plug in the real RAG agent.
The interface contract is:
    respond(question: str, db: Session) -> tuple[str, list[int]]
    returns: (reply_text, list_of_source_ids_cited)
"""
import logging
from sqlalchemy.orm import Session
from app.models import KnowledgeChunk, KnowledgeSource

logger = logging.getLogger(__name__)

_MAX_CHUNKS = 3
_SNIPPET_CHARS = 400


def respond(question: str, db: Session) -> tuple[str, list[int]]:
    """Return an AI reply and the source IDs cited.

    Current implementation: naive keyword / substring search over chunk text.
    Replace the body of this function with a real RAG / LLM call when ready.
    The caller (chat router) stores the returned text and source_ids verbatim.

    Args:
        question: The user's message text.
        db: Active SQLAlchemy session.

    Returns:
        A 2-tuple of (reply_text, cited_source_ids).
    """
    if not question.strip():
        return "Please ask a question about the uploaded knowledge.", []

    # ── Naive search: score each chunk by keyword overlap ──────────────────
    terms = [t.lower() for t in question.split() if len(t) > 2]

    all_chunks: list[KnowledgeChunk] = (
        db.query(KnowledgeChunk)
        .join(KnowledgeSource)
        .filter(KnowledgeSource.ingestion_status == "indexed")
        .all()
    )

    if not all_chunks:
        return (
            "No knowledge has been indexed yet. Please ask an admin to upload "
            "and index some documents first.",
            [],
        )

    scored: list[tuple[int, KnowledgeChunk]] = []
    for chunk in all_chunks:
        text_lower = chunk.text.lower()
        score = sum(1 for t in terms if t in text_lower)
        if score > 0:
            scored.append((score, chunk))

    if not scored:
        return (
            "I searched the knowledge base but could not find information "
            f'directly related to "{question}". Try rephrasing your question '
            "or ask an admin to add more relevant documents.",
            [],
        )

    # Sort by score descending, take top N
    scored.sort(key=lambda x: x[0], reverse=True)
    top_chunks = [chunk for _, chunk in scored[:_MAX_CHUNKS]]

    # ── Build reply ────────────────────────────────────────────────────────
    source_ids: list[int] = []
    parts: list[str] = [
        f"Based on the indexed knowledge, here are the most relevant excerpts "
        f'for "{question}":\n'
    ]

    seen_sources: set[int] = set()
    for i, chunk in enumerate(top_chunks, 1):
        source = chunk.source
        snippet = chunk.text[:_SNIPPET_CHARS].strip()
        if len(chunk.text) > _SNIPPET_CHARS:
            snippet += "…"
        parts.append(f"\n**Excerpt {i}** — *{source.name}* (v{source.version}):\n{snippet}")
        if source.id not in seen_sources:
            source_ids.append(source.id)
            seen_sources.add(source.id)

    parts.append(
        "\n\n---\n*This response was generated by the placeholder AI responder. "
        "Source traceability: the excerpts above come directly from the indexed "
        "knowledge base. Swap `ai_responder.py` → `respond()` to connect the "
        "real RAG/LLM agent.*"
    )

    logger.info(
        "ai_responder: question=%r, chunks_searched=%d, top_chunks=%d, sources=%s",
        question[:60],
        len(all_chunks),
        len(top_chunks),
        source_ids,
    )

    return "".join(parts), source_ids
